# Generated by Django 6.0.4 on 2026-04-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeFormacao", models.CharField(max_length=150)),
                ("instituicao", models.CharField(max_length=150)),
                ("duracaoFormacao", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "nomeInteresse",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("descricaoInteresse", models.TextField()),
                ("categoriaInteresse", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "nomeCurso",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("descricaoCurso", models.TextField()),
                ("creditosCurso", models.IntegerField()),
                ("duracao", models.CharField(max_length=50)),
                ("formato", models.CharField(max_length=50)),
                ("website", models.URLField(blank=True, null=True)),
                ("faculdade", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeProjeto", models.CharField(max_length=150)),
                ("descricaoProjeto", models.TextField()),
                ("anoRealizacao", models.IntegerField()),
                ("linkGitHub", models.URLField(blank=True, null=True)),
                (
                    "fotoProjeto",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("linksVideo", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "nomeTecnologia",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("descricaoTecnologia", models.TextField()),
                (
                    "logotipo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("linkSite", models.URLField(blank=True, null=True)),
                ("tipoTecnologia", models.CharField(max_length=50)),
                ("classificacao", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapas", models.CharField(max_length=100)),
                (
                    "registos",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("descricaoDecisoes", models.TextField()),
                ("justificacaoDecisoes", models.TextField()),
                ("errosEncontrados", models.TextField()),
                ("solucao", models.TextField()),
                ("usoIA", models.TextField()),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makingof_logs",
                        to="portfolioPessoal.projeto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True,
                related_name="projetos_onde_usada",
                to="portfolioPessoal.tecnologia",
            ),
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tituloTFC", models.CharField(max_length=200)),
                ("descricaoTFC", models.TextField()),
                ("autores", models.CharField(max_length=250)),
                ("anoRealizacao", models.IntegerField()),
                ("classificacaoTFC", models.IntegerField()),
                ("linkTFC", models.URLField(blank=True, null=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfcs",
                        to="portfolioPessoal.licenciatura",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tfcs_onde_usada",
                        to="portfolioPessoal.tecnologia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "idUC",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nomeUC", models.CharField(max_length=150)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("creditosUC", models.IntegerField()),
                ("descricaoUC", models.TextField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                ("linkUC", models.URLField(blank=True, null=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolioPessoal.licenciatura",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ucs_onde_usada",
                        to="portfolioPessoal.tecnologia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="uc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolioPessoal.unidadecurricular",
            ),
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                ("idDocente", models.AutoField(primary_key=True, serialize=False)),
                ("nomeDocente", models.CharField(max_length=150)),
                ("linkPerfilUniversidade", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "tfcs_orientados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="orientadores",
                        to="portfolioPessoal.tfc",
                    ),
                ),
                (
                    "ucs_lecionadas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="equipa_docente",
                        to="portfolioPessoal.unidadecurricular",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeCompetencia", models.CharField(max_length=100)),
                ("descricaoCompetencia", models.TextField()),
                ("categoria", models.CharField(max_length=50)),
                (
                    "formacoes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias_validas",
                        to="portfolioPessoal.formacao",
                    ),
                ),
                (
                    "interesses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias_validas",
                        to="portfolioPessoal.interesse",
                    ),
                ),
                (
                    "projetos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias_validas",
                        to="portfolioPessoal.projeto",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias_validas",
                        to="portfolioPessoal.tecnologia",
                    ),
                ),
                (
                    "tfcs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias_validas",
                        to="portfolioPessoal.tfc",
                    ),
                ),
                (
                    "ucs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias_validas",
                        to="portfolioPessoal.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
