# Generated by Django 6.0.4 on 2026-04-10 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPessoal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="bibliografia",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="metodologia",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="metodos_avaliacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="programa",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unidades_curriculares",
                to="portfolioPessoal.licenciatura",
            ),
        ),
    ]
