# Generated by Django 6.0.4 on 2026-04-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPessoal", "0002_unidadecurricular_bibliografia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docente",
            name="tfcs_orientados",
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.ManyToManyField(
                blank=True,
                related_name="tfcs_orientados",
                to="portfolioPessoal.docente",
            ),
        ),
    ]
