# Generated by Django 6.0.4 on 2026-04-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPessoal", "0003_remove_docente_tfcs_orientados_tfc_orientadores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="idDocente",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="descricaoUC",
            field=models.TextField(blank=True, null=True),
        ),
    ]
