# Generated by Django 6.0.4 on 2026-04-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPessoal", "0004_alter_docente_iddocente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="idDocente",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
