# Generated by Django 6.0.4 on 2026-04-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPessoal", "0005_alter_docente_iddocente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competencia",
            name="projetos",
        ),
        migrations.AddField(
            model_name="projeto",
            name="competencias",
            field=models.ManyToManyField(
                blank=True,
                related_name="projetos_associados",
                to="portfolioPessoal.competencia",
            ),
        ),
    ]
