# Generated by Django 6.0.4 on 2026-04-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPessoal", "0006_remove_competencia_projetos_projeto_competencias"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competencia",
            name="ucs",
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="competencias",
            field=models.ManyToManyField(
                blank=True,
                related_name="ucs_associadas",
                to="portfolioPessoal.competencia",
            ),
        ),
    ]
