# Generated by Django 6.0.4 on 2026-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolioPessoal",
            "0008_alter_competencia_options_alter_docente_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="linksVideo",
        ),
        migrations.AddField(
            model_name="projeto",
            name="videoProjeto",
            field=models.FileField(blank=True, null=True, upload_to="projetos/videos/"),
        ),
    ]
