# Generated by Django 6.0.4 on 2026-04-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPessoal", "0009_remove_projeto_linksvideo_projeto_videoprojeto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="videoProjeto",
        ),
        migrations.AddField(
            model_name="projeto",
            name="linksVideo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
