# Generated by Django 6.0.4 on 2026-04-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPessoal", "0010_remove_projeto_videoprojeto_projeto_linksvideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="registos",
            field=models.FileField(blank=True, null=True, upload_to="makingof/"),
        ),
    ]
