# Generated by Django 6.0.4 on 2026-04-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPessoal", "0011_alter_makingof_registos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="curso",
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="cursos",
            field=models.ManyToManyField(
                blank=True,
                related_name="unidades_curriculares",
                to="portfolioPessoal.licenciatura",
            ),
        ),
    ]
