# Generated by Django 6.0.4 on 2026-04-29 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPessoal", "0012_remove_unidadecurricular_curso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="categoria",
            field=models.CharField(max_length=50, verbose_name="Categoria"),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="descricaoCompetencia",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="formacoes",
            field=models.ManyToManyField(
                blank=True,
                related_name="competencias_validas",
                to="portfolioPessoal.formacao",
                verbose_name="Formações Relacionadas",
            ),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="interesses",
            field=models.ManyToManyField(
                blank=True,
                related_name="competencias_validas",
                to="portfolioPessoal.interesse",
                verbose_name="Interesses Relacionados",
            ),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="nomeCompetencia",
            field=models.CharField(max_length=100, verbose_name="Competência"),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True,
                related_name="competencias_validas",
                to="portfolioPessoal.tecnologia",
                verbose_name="Tecnologias Utilizadas",
            ),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="tfcs",
            field=models.ManyToManyField(
                blank=True,
                related_name="competencias_validas",
                to="portfolioPessoal.tfc",
                verbose_name="TFCs Associados",
            ),
        ),
        migrations.AlterField(
            model_name="docente",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="docente",
            name="idDocente",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="Docente ID",
            ),
        ),
        migrations.AlterField(
            model_name="docente",
            name="linkPerfilUniversidade",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link do Perfil Universitário"
            ),
        ),
        migrations.AlterField(
            model_name="docente",
            name="nomeDocente",
            field=models.CharField(max_length=150, verbose_name="Nome do Docente"),
        ),
        migrations.AlterField(
            model_name="docente",
            name="ucs_lecionadas",
            field=models.ManyToManyField(
                blank=True,
                related_name="equipa_docente",
                to="portfolioPessoal.unidadecurricular",
                verbose_name="UCs Lecionadas",
            ),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="duracaoFormacao",
            field=models.CharField(max_length=50, verbose_name="Duração"),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="instituicao",
            field=models.CharField(max_length=150, verbose_name="Instituição"),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="nomeFormacao",
            field=models.CharField(max_length=150, verbose_name="Nome da Formação"),
        ),
        migrations.AlterField(
            model_name="interesse",
            name="categoriaInteresse",
            field=models.CharField(max_length=50, verbose_name="Categoria"),
        ),
        migrations.AlterField(
            model_name="interesse",
            name="descricaoInteresse",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="interesse",
            name="nomeInteresse",
            field=models.CharField(
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Nome do Interesse",
            ),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="creditosCurso",
            field=models.IntegerField(verbose_name="Créditos (ECTS)"),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="descricaoCurso",
            field=models.TextField(verbose_name="Descrição do Curso"),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="duracao",
            field=models.CharField(max_length=50, verbose_name="Duração"),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="faculdade",
            field=models.CharField(max_length=150, verbose_name="Faculdade"),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="formato",
            field=models.CharField(max_length=50, verbose_name="Formato de Ensino"),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="nomeCurso",
            field=models.CharField(
                max_length=200, primary_key=True, serialize=False, verbose_name="Curso"
            ),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="website",
            field=models.URLField(
                blank=True, null=True, verbose_name="Website do Curso"
            ),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="descricaoDecisoes",
            field=models.TextField(verbose_name="Descrição das Decisões"),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="errosEncontrados",
            field=models.TextField(verbose_name="Erros Encontrados"),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="etapas",
            field=models.CharField(max_length=100, verbose_name="Etapas do Processo"),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="justificacaoDecisoes",
            field=models.TextField(verbose_name="Justificação das Decisões"),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="projeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="makingof_logs",
                to="portfolioPessoal.projeto",
                verbose_name="Projeto Relacionado",
            ),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="registos",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="makingof/",
                verbose_name="Ficheiros de Registo",
            ),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="solucao",
            field=models.TextField(verbose_name="Solução Aplicada"),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="usoIA",
            field=models.TextField(verbose_name="Uso de Inteligência Artificial"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="anoRealizacao",
            field=models.IntegerField(verbose_name="Ano de Realização"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="competencias",
            field=models.ManyToManyField(
                blank=True,
                related_name="projetos_associados",
                to="portfolioPessoal.competencia",
                verbose_name="Competências Demonstradas",
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricaoProjeto",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="fotoProjeto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projetos/",
                verbose_name="Foto do Projeto",
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="linkGitHub",
            field=models.URLField(blank=True, null=True, verbose_name="Link do GitHub"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="linksVideo",
            field=models.URLField(blank=True, null=True, verbose_name="Link do Vídeo"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="nomeProjeto",
            field=models.CharField(max_length=150, verbose_name="Nome do Projeto"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True,
                related_name="projetos_onde_usada",
                to="portfolioPessoal.tecnologia",
                verbose_name="Tecnologias Aplicadas",
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="uc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolioPessoal.unidadecurricular",
                verbose_name="Unidade Curricular",
            ),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="classificacao",
            field=models.IntegerField(verbose_name="Classificação"),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="descricaoTecnologia",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="linkSite",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link do Site Oficial"
            ),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="logotipo",
            field=models.ImageField(
                blank=True, null=True, upload_to="tecnologias/", verbose_name="Logotipo"
            ),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="nomeTecnologia",
            field=models.CharField(
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Nome da Tecnologia",
            ),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="tipoTecnologia",
            field=models.CharField(max_length=50, verbose_name="Tipo de Tecnologia"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="anoRealizacao",
            field=models.IntegerField(verbose_name="Ano de Realização"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autores",
            field=models.CharField(max_length=250, verbose_name="Autores"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="classificacaoTFC",
            field=models.IntegerField(verbose_name="Classificação Final"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tfcs",
                to="portfolioPessoal.licenciatura",
                verbose_name="Curso",
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="descricaoTFC",
            field=models.TextField(verbose_name="Descrição do Trabalho"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="linkTFC",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link do Trabalho"
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientadores",
            field=models.ManyToManyField(
                blank=True,
                related_name="tfcs_orientados",
                to="portfolioPessoal.docente",
                verbose_name="Orientadores",
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True,
                related_name="tfcs_onde_usada",
                to="portfolioPessoal.tecnologia",
                verbose_name="Tecnologias Utilizadas",
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tituloTFC",
            field=models.CharField(max_length=200, verbose_name="Título do TFC"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="ano",
            field=models.IntegerField(verbose_name="Ano Curricular"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="bibliografia",
            field=models.TextField(blank=True, null=True, verbose_name="Bibliografia"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="competencias",
            field=models.ManyToManyField(
                blank=True,
                related_name="ucs_associadas",
                to="portfolioPessoal.competencia",
                verbose_name="Competências Adquiridas",
            ),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="creditosUC",
            field=models.IntegerField(verbose_name="Créditos (ECTS)"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="cursos",
            field=models.ManyToManyField(
                blank=True,
                related_name="unidades_curriculares",
                to="portfolioPessoal.licenciatura",
                verbose_name="Cursos",
            ),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="descricaoUC",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição da UC"
            ),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="idUC",
            field=models.CharField(
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="Unidade Curricular ID",
            ),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="ucs/", verbose_name="Imagem da UC"
            ),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="linkUC",
            field=models.URLField(blank=True, null=True, verbose_name="Link da UC"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="metodologia",
            field=models.TextField(blank=True, null=True, verbose_name="Metodologia"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="metodos_avaliacao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Métodos de Avaliação"
            ),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="nomeUC",
            field=models.CharField(max_length=150, verbose_name="Nome da UC"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True, null=True, verbose_name="Objetivos"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="programa",
            field=models.TextField(blank=True, null=True, verbose_name="Programa"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.IntegerField(verbose_name="Semestre"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True,
                related_name="ucs_onde_usada",
                to="portfolioPessoal.tecnologia",
                verbose_name="Tecnologias Envolvidas",
            ),
        ),
    ]
