# Generated by Django 6.0.4 on 2026-05-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPessoal", "0013_alter_competencia_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="nomeDocente",
            field=models.TextField(verbose_name="Nome do Docente"),
        ),
    ]
